apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
  labels:
    app: dev
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dev
  template:
    metadata:
      labels:
        app: dev
    spec:
      containers:
        - name: cont1
          image: 736530791180.dkr.ecr.ap-south-1.amazonaws.com/myrepo:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"
            limits:
              cpu: "500m"
              memory: "256Mi"
          env:
            - name: ENV
              value: "dev"